### PR TITLE
fix color bug after many event

### PR DESCRIPTION
**Pull request by faalicante**
changed the drawing volumes each event displayed
passive volumes are drawn only at the beginning
filled volumes are redrawn each event so as to empy them
I run over 500 events and no color bug, but it seems to slow down a bit

### CODE REVIEW

**Review by antonioiuliano2 — DISMISSED** [review]
Removed function emptyNodes(),

Inserted drawing condition

**Comment by antonioiuliano2** [comment]
We are currenly working to solve the conflicts

**Review by antonioiuliano2 — APPROVED** [review]

**Comment by antonioiuliano2** [comment]
Fabio and I solved the conflicts and the pull request can be merged

**Review by ThomasRuf — APPROVED** [review]
ok

**Pull request merged**
