### PR TITLE
Fillgeometry

### PR DESCRIPTION
**Pull request by faalicante**
update on 2d event display
added the passive volumes
hits are shown by colored nodes
tracks are available

### CODE REVIEW

**Review by ThomasRuf — COMMENTED** [review]
Why do you switch to the local coordinate system? In this coordinate system, the z-axis does not correspond to the nominal beam axis. It is also not the system used for the tracking. You would need to change the drawing of tracks.

**Comment by faalicante** [comment]
> Why do you switch to the local coordinate system? In this coordinate system, the z-axis does not correspond to the nominal beam axis. It is also not the system used for the tracking. You would need to change the drawing of tracks.

Actually I am using the global coordinate system. The trans2local is set 'True' because I did some tests, but I'm never using the locA coordinates in the code, just globA. Of course we can set it to False and it should be the same.

**Comment by ThomasRuf** [comment]
yes, better to change the value, otherwise it is confusing.

**Comment by faalicante** [comment]
Sure I will do it right now. Should I make another pull request then?

**Comment by ThomasRuf** [comment]
Some comments about the appearing:
image

the green of the iron blocks look to dominant for me. Could you reduce the contrast, making it lighter?

something strange with the display of the bars. some bars are drawn some are not drawn. Scrolling through more events, it seems only bars are drawn which fired in the past.

**Comment by ThomasRuf** [comment]
I assume if you make a new commit, you don't have to do anything with the pull request. Should be automatic.

**Comment by faalicante** [comment]
This is strange, it looks very different when I run it
Schermata del 2022-07-05 14-44-19

**Comment by faalicante** [comment]
This is strange. It looks very different when I run it
Schermata del 2022-07-18 14-27-39

**Comment by ThomasRuf** [comment]
first event
image

running over many events (which is rather slow), most of the bars start to appear, but also a box in the left bottom corner.
image

**Comment by ThomasRuf** [comment]
logo = ROOT.TImage.Open('/home/fabio/Immagini/Large__SND_Logo_black_cut.png')
this cannot work. You need to add this file to the pull reuqest.

**Comment by ThomasRuf** [comment]
also the time stamp is wrong in the display:
eventTree.EventHeader.GetEventTime()
1571114810942.0

image

**Comment by faalicante** [comment]
> 



> logo = ROOT.TImage.Open('/home/fabio/Immagini/Large__SND_Logo_black_cut.png') this cannot work. You need to add this file to the pull reuqest.

this for sure. I completely forgot to add the file. In which folder should I put it?

**Comment by faalicante** [comment]
> also the time stamp is wrong in the display: eventTree.EventHeader.GetEventTime() 1571114810942.0
> 
> image

seems like there is no more space for numbers in the pad, comparing with my view also the text "SND@LHC Experiment, CERN" is missing CERN.
I don't know why this is so different from what I see

**Comment by ThomasRuf** [comment]
you could copy the logo to the sndsw/shipLHC directory

**Comment by faalicante** [comment]
I fixed the issues. Tomorrow in the morning I will commit. Sorry for the inconvenient

**Comment by faalicante** [comment]
I will do another pull request and close this one in order to have cleaner commit history. I incorporated your comments and tried the new branch on lxplus and it works. Shall I proceed with the new pull request?

**Comment by ThomasRuf** [comment]
OK

**Pull request closed without merging**
