### PR TITLE
Shifter monitorng plots

### PR DESCRIPTION
**Pull request by siilieva**
Introducing  `/shifter` and `/expert` folders in the monitoring ROOT files.
The purpose is to make it easier for the shifter to look at fewer summary plots only, while experts can still look at the numerous useful original monitoring plots. These plots were consulted with Gerardo as Run Coordinator and discussed during run meeting.

All verified to work - this branch is now used to generate the monitoring plots.

### CODE REVIEW

**Comment by olantwin** [comment]
Review coming Monday.

**Review by olantwin — DISMISSED** [review]
The monitoring code generally is a bit of a mess, but your changes look fine.

**Comment by olantwin** [comment]
Which comments are new?
Because of the force push, there is no way for me to tell what changed since I reviewed the code originally.

**Comment by siilieva** [comment]
comments on the plots arrived late and I was even slower pushing them. We already use this branch for the monitoring on vm machines.
It is the same topic, so I pushed here. 
One can always check the git hash of the last forced push, but that is not the point. Will split next time @olantwin

**Review by olantwin — APPROVED** [review]
I trust that you know what you're doing 🙂

**Comment by siilieva** [comment]
> I trust that you know what you're doing 🙂

Grazie!

**Pull request merged**
