### PR TITLE
Muon pattern recognition

### PR DESCRIPTION
**Pull request by cvilelahep**
Algorithm implemented in `python/SndlhcMuonReco.py` and run script in `shipLHC/run_muonRecoSND.py`
```
usage: run_muonRecoSND.py [-h] -f INPUTFILE -g GEOFILE [-n NEVENTS]
                          [-i FIRSTEVENT] [-t TOLERANCE] [--use_scifi]
                          [--no-use_scifi] [--use_mufi] [--no-use_mufi]
                          [--no-passthrough]

optional arguments:
  -h, --help            show this help message and exit
  -f INPUTFILE, --inputFile INPUTFILE
                        single input file
  -g GEOFILE, --geoFile GEOFILE
                        geofile
  -n NEVENTS, --nEvents NEVENTS
                        number of events to process
  -i FIRSTEVENT, --firstEvent FIRSTEVENT
                        First event of input file to use
  -t TOLERANCE, --tolerance TOLERANCE
                        How far away from Hough line hits assigned to the muon
                        can be. In cm.
  --use_scifi           Use SciFi hits. [Default]
  --no-use_scifi        Do not use SciFi hits.
  --use_mufi            Use Muon Filter hits. Muon tracks are required to have
                        three DS Muon Filter planes hit. [Default]
  --no-use_mufi         Do not use Muon Filter hits. The triplet condition
                        will be based on SciFi hits.
  --no-passthrough      [PASSTHROUGH IS CURRENTLY BROKEN!] By default all
                        input data is passed through to the output. Use this
                        flag to keep only reconstructed tracks in the output
                        file.
```
## Output
The output is stored in a collection named `Reco_MuonTracks`. `genfit` track objects are used.

## Notes
There are a couple of issues which will be fixed in the future:
 - To run on raw data files, a file named `rootmanager.dat` with the contents `treename=rawConv` must be placed in `${SNDSW_ROOT}/config/`. This tells FairRoot to look for a tree named `rawConv` instead of the default `cbmsim`. To run on simulation, the file must be removed.
   - The simulated and real data tree names will be the same in the future and this will no longer be necessary. See slide 2 in @ThomasRuf's [February 22 slides](https://indico.cern.ch/event/1125527/contributions/4750438/attachments/2395686/4096212/SND-software-Tasks-VII.pdf).
 - Ideally there would be an option to either pass all the input data through to the output file or to save only the reconstructed tracks. At the moment this functionality is broken and only the tracks are saved on the output. Friend trees can be used to match the tracks to the rest of the event.
 
## Validation
Just a few cherry-picked examples.
### Muon neutrino simulation
image

### Background muon simulation
image
Same event, but only scifi hits used in track reconstruction and zoomed in.
image

### H6 data
image
Same event, but only scifi hits used in track reconstruction and zoomed in.
image

### CODE REVIEW

**Review by ThomasRuf — APPROVED** [review]
OK for testing. 

One question, if the event loop is placed in the python script:
for n in range(options.firstEvent, options.firstEvent + options.nEvents):
  run.Run(n,1)
  "can I do something with the tracks"?

**Comment by ThomasRuf** [comment]
Additional comment: we need an option to suppress downloading the input file, in case no track persistency is needed. I have currently a slow internet connection, and this is a show stopper for making quick tests.

**Comment by ThomasRuf** [comment]
it seems, I can get control of the eventLoop:

replacing run.Run(options.firstEvent, options.firstEvent + options.nEvents) by

T = sink.GetOutTree()
eventTree = source.GetInTree()
for n in range(options.firstEvent, options.firstEvent + options.nEvents):
  rc = eventTree.GetEvent(n)
  muon_reco_task.Exec(0)
  if T.Reco_MuonTracks.GetEntries()>0: 1/0

**Comment by ThomasRuf** [comment]
aTrack = T.Reco_MuonTracks[0]
s = aTrack.getFitStatus()
s.getChi2()
6.810829481611963
s.getNdf()
3.0

running on real data from H6.
 
interesting to note: there is no need for the rootmanager.dat file specifying the name of the TTree for raw data converted by the C++ task. Reason, these files contain cbmsim and rawConv pointing to the same TTree.

**Comment by cvilelahep** [comment]
> In addition, after downloading 4.5GB, it makes a copy, eating another 4.5GB disk space. Instead of doing a copy, I would suggest that the copied input file is renamed, and opened with update option.

Sorry about this, clearly a terrible bit of code... 
I can't remember why the file is being copied... Probably a remnant of some different handling of the I/O -- I tried a few options while I was figuring out how FairRoot handled the files. And I guess I didn't notice how bad this was because I was mostly testing on small simulated files....
I don't think I'll be able to work on this in the next couple of days, but I'll fix it early next week and implement the other options you requested above.

**Comment by ThomasRuf** [comment]
No problem, I am just listing my observations. I think the most important step would be to run without an output file, just read data from EOS and make tracks per event. If you know or have an idea how to configure FairRunAna for this, let me know.  I am afraid, without an output file, it will not create the corresponding container for Reco_MuonTracks.

Another observation: Passthrough() method is meant to make a copy of the input file? As it is, it would not scale, I mean it would need to be changed whenever new containers are added to the original file. Right now, I see that it is missing the EventHeader for raw data, and it is copying MC information which does not exist for raw data.

**Comment by ThomasRuf** [comment]
I managed to include the hough transform in the 2dEventdisplay script. It does work in principle:
image

but very often it dose not find the track, despite enough Scifi hits. running with option --no-use_mufi
image

the outputfile is set to memory only: 
outFile = ROOT.TMemFile('dummy','CREATE')
sink = ROOT.FairRootFileSink(outFile)

**Comment by ThomasRuf** [comment]
can find two correct tracks if occupancy is not too high in scifi
image

**Comment by cvilelahep** [comment]
> but very often it dose not find the track, despite enough Scifi hits. running with option --no-use_mufi

One thing to try here is using the `--tolerance` parameter. By default, a track candidate is only accepted if it intersects at least one hit in three stations. This works well for the larger scintillator bars but might be too strict for Scifi-only tracking, especially in real data where there slight misalignments might have an impact.

Setting the `--tolerance` parameter to something like one channel width (0.025) will allow hits just missed by the track to be associated to the track anyway. This will make it easier for the triplet condition to be met and might help improve the Scifi-only tracking efficiency.

> can find two correct tracks if occupancy is not too high in scifi

Cool! :)

**Comment by ThomasRuf** [comment]
OK, with --tolerance = 0.05, it does improve the track finding. But it seems that the mufi hits are not included in the track, even if they look well aligned with the scifi track. Looping over the track measurements, shows no sign of a mufi detid:
for aTrack in eventTree.fittedTracks:
...    for x in aTrack.getPointsWithMeasurement(): print( x.getRawMeasurement().getDetId())

**Comment by cvilelahep** [comment]
> But it seems that the mufi hits are not included in the track, even if they look well aligned with the scifi track.

Just to make sure: do you see this behaviour with the `--no-use_mufi` option or without it?

**Comment by ThomasRuf** [comment]
with --use_mufi --use_scifi --tolerance 0.05
image

with --no-use_mufi --use_scifi 
image

could there be a problem because in H6 Scifi is behind MuFilter and not in front?

**Comment by cvilelahep** [comment]
> could there be a problem because in H6 Scifi is behind MuFilter and not in front?

Ah! That could be it! The code assumes the Scifi is in front of the MuFilter when ordering the hits in Z for the Kalman fitter. I'll fix this.

**Comment by ThomasRuf** [comment]
I noticed that there is no attempt to make ScifiClusters by grouping neighboring Scifihits. By making a cluster and calculating the position using the weighted position of the hits, improves the space resolution. One other side effect I noticed when I was looking for unique tracks, there are tracks which share no common Scifihit, however the share hits which are neighbours, so indeed not really unique.

**Comment by ThomasRuf** [comment]
one more observation: looking at the detIDs of the fitted tracks, I noticed that detectorIDs can appear several times.
[1002014, 1002013, 1002015, 1002015, 1002014, 1002016, 2002001, 2002000, 2002002, 2102028, 2102027, 2102029, 3001114, 3001113, 3001115, 3001115, 3001114, 3001116, 3102027, 3102026, 3102028, 4001099, 4001098, 4001100, 4102007, 4102006, 4102008, 4102008, 4102007, 4102009]
what does it mean?

**Pull request merged**
