### PR TITLE
[WIP] Merge/integrate @abuonaura's prototype implementation

### PR DESCRIPTION
**Pull request by olantwin**
TODOs:

- [ ] Fix line endings
- [ ] strip out modifications to irrelevant files

### CODE REVIEW

**Comment by antonioiuliano2** [comment]
Hi Oliver,
first, thank you for starting this new repository and inviting me.

I see the same problems that I have noticed during my test of merging with FairShip updates: some files have conflicts even if they are not related to Annarita's changes (ShipMuonShield and veto, for examples). 

If I look at the changes it seems to have re-written the code anew. Do you know if It is due to end-of-line differences? I recall an issue solved recently in the main FairShip repository, on this subject.

**Comment by olantwin** [comment]
Yes, this is definitely due to the EOL differences. I don't think this is something we ever properly solved in FairShip, see  e.g. ShipSoft/FairShip#360 .

For this pull request, it should be not too difficult to ignore those changes manually though.

**Comment by antonioiuliano2** [comment]
Hi Oliver, are you encountering some problems with this pull request I can help you with?

Since I need to update the geometry of the target, I would like to work on a fork of this repository, but of course it would be safer to solve these conflicts first.

**Comment by olantwin** [comment]
If you could try rebasing it, that would be amazing. I hope this fixed the line endings issue.

There are no concrete problems I am aware of right now, I just haven't found the time to review the pull request in detail yet.

**Comment by antonioiuliano2** [comment]
Dear Oliver,
unfortunately, as soon as I clone this repository, git will complain about modifications in veto/veto.cxx and veto/veto.h.
It does let me neither rebase annarita branch, nor merge it.
What can we do?

**Comment by antonioiuliano2** [comment]
There are also a lot of "unusual" files in the modified files, such as temporary files and calorimetry files (which should not involve SND@LHC at all).

**Comment by olantwin** [comment]
> There are also a lot of "unusual" files in the modified files, such as temporary files and calorimetry files (which should not involve SND@LHC at all).

Yes, we will need to strip them out of the pull request. Thanks for bringing this up!

**Comment by olantwin** [comment]
> Dear Oliver,
> unfortunately, as soon as I clone this repository, git will complain about modifications in veto/veto.cxx and veto/veto.h.
> It does not let me rebase Annarita's code
> What can we do?

I will play around with the line ending normalisation to figure out how to best deal with this.

**Comment by antonioiuliano2** [comment]
> > Dear Oliver,
> > unfortunately, as soon as I clone this repository, git will complain about modifications in veto/veto.cxx and veto/veto.h.
> > It does not let me rebase Annarita's code
> > What can we do?
> 
> I will play around with the line ending normalisation to figure out how to best deal with this.

Thank you, in the meantime @abuonaura could you please give us a list of all the modifications which are intentional and we should keep? This should provide a big help for the second issue. As far as I know, the fundamental changes are:

* the introduction of the shiplhc folder;
* the addition of this folder in CMakeLists.txt and shipdata/ShipDetectorList.h;
* the introduction of the files geometry/shipLHC_geom_config.py, python/shipLHC_conf.py;
* the new option in macro/run_simScript.py; 
* the new displays macro/eventDisplay_shipLHC.py and macro/eventDisplay_shipLHC_std.py;
* the new medium in geometry/media.geo;
* some minor printout changes in shipgen/GenieGenerator.cxx

Is there any other file you modified that we should add to the pull request? Do the modifications in ecal, hcal, MufluxDigi and shipPat (shipvertex, etc.) mean something in the SND@LHC code?

**Comment by abuonaura** [comment]
> > > Dear Oliver,
> > > unfortunately, as soon as I clone this repository, git will complain about modifications in veto/veto.cxx and veto/veto.h.
> > > It does not let me rebase Annarita's code
> > > What can we do?
> > 
> > 
> > I will play around with the line ending normalisation to figure out how to best deal with this.
> 
> Thank you, in the meantime @abuonaura could you please give us a list of all the modifications which are intentional and we should keep? This should provide a big help for the second issue. As far as I know, the fundamental changes are:
> 
>     * the introduction of the **shiplhc** folder;
> 
>     * the addition of this folder in **CMakeLists.txt** and **shipdata/ShipDetectorList.h**;
> 
>     * the introduction of the files **geometry/shipLHC_geom_config.py**, **python/shipLHC_conf.py**;
> 
>     * the new option in **macro/run_simScript.py**;
> 
>     * the new displays **macro/eventDisplay_shipLHC.py** and **macro/eventDisplay_shipLHC_std.py**;
> 
>     * the new medium in **geometry/media.geo**;
> 
>     * some minor printout changes in **shipgen/GenieGenerator.cxx**
> 
> 
> Is there any other file you modified that we should add to the pull request? Do the modifications in ecal, hcal, MufluxDigi and shipPat (shipvertex, etc.) mean something in the SND@LHC code?

Dear Antonio,
the modifications I listed in my presentation are the only ones I did to implement the SND simulation.
I did not modify anything for ecal, hcal etc.

**Comment by antonioiuliano2** [comment]
> > > > Dear Oliver,
> > > > unfortunately, as soon as I clone this repository, git will complain about modifications in veto/veto.cxx and veto/veto.h.
> > > > It does not let me rebase Annarita's code
> > > > What can we do?
> > > 
> > > 
> > > I will play around with the line ending normalisation to figure out how to best deal with this.
> > 
> > 
> > Thank you, in the meantime @abuonaura could you please give us a list of all the modifications which are intentional and we should keep? This should provide a big help for the second issue. As far as I know, the fundamental changes are:
> > ```
> > * the introduction of the **shiplhc** folder;
> > 
> > * the addition of this folder in **CMakeLists.txt** and **shipdata/ShipDetectorList.h**;
> > 
> > * the introduction of the files **geometry/shipLHC_geom_config.py**, **python/shipLHC_conf.py**;
> > 
> > * the new option in **macro/run_simScript.py**;
> > 
> > * the new displays **macro/eventDisplay_shipLHC.py** and **macro/eventDisplay_shipLHC_std.py**;
> > 
> > * the new medium in **geometry/media.geo**;
> > 
> > * some minor printout changes in **shipgen/GenieGenerator.cxx**
> > ```
> > 
> > 
> > Is there any other file you modified that we should add to the pull request? Do the modifications in ecal, hcal, MufluxDigi and shipPat (shipvertex, etc.) mean something in the SND@LHC code?
> 
> Dear Antonio,
> the modifications I listed in my presentation are the only ones I did to implement the SND simulation.
> I did not modify anything for ecal, hcal etc.

Dear Annarita,

thank you very much for your answer. I have just re-checked your presentation, and there are the same files I have reported here. I am now trying then to reset all other changes, keeping only these ones. Then I will test a re-build and a simulation in this condition.

Best regards,
Antonio

**Comment by olantwin** [comment]
Close in favour of #2

**Pull request closed without merging**
