### PR TITLE
Monitoring task with cpp raw data conversion

### PR DESCRIPTION
**Pull request by siilieva**

### CODE REVIEW

**Review by ThomasRuf — COMMENTED** [review]
SndlhcTracking: don't understand why the changes are needed. In any case, I was working on an approved scifi pattern recognition, and modified the code. Maybe this part could be left out from the pull request? Or I approve the pull request and overwrite afterwards with my changes?

convertRawData looks ok. Have also some small cjanges which I can add afterwards.

scifi monitoring: OK. Have many changes to this one.

**Comment by siilieva** [comment]
While testing, in SndlhcTracking(called from [beamSpot ](https://github.com/SND-LHC/sndsw/blob/truf-monitoring/shipLHC/scripts/Mufi_monitoring.py) in Mufi_monitoring) I was getting an error due to accessing TClonesArray via operator [ ] in [here](https://github.com/SND-LHC/sndsw/pull/97/files/a0820fb495b7b605a1304dacabd603a772f28c62#diff-3bb4614a221f55c67e91c945957856c521fc44d9e63acebf0eaf7480c0991151L116).  That only happened in online mode using cpp conversion.

**Comment by ThomasRuf** [comment]
This has been fixed, I am just running some tests now.

**Review by ThomasRuf — APPROVED** [review]
Will put it into the master and then start to apply my modifcations

**Review by ThomasRuf — COMMENTED** [review]
there is an upcoming issue with this line:
 ioman.RegisterInputObject('withGeoFile', ROOT.TObjString(str(int(options.withGeoFile)))) 

I have now started to use this option either to be NONE or containing the name of the geofile.

**Pull request merged**
