### PR TITLE
Set target position in new geometry2

### PR DESCRIPTION
**Pull request by antonioiuliano2**
Dear all,

this pull request contains all my current changes to the NewGeometry2 branch (applying the transformation from survey and physics reference systems).

The changes in this pull request are the following:

* Adding the array of positions of wall and scifi chambers from the technical drawings;
* Adding an external layer to the wall;

I am now going to inspect and update the positions of the iron boxes of the MuonFilter, since there are overlaps in these volumes:

 = Overlap ov00000: cave/Detector_0/volMuFilter_1/volFeBlock_3 overlapping cave/Tunnel_1/VTI18_1 ovlp=3.56054
 = Overlap ov00001: cave/Detector_0/volMuFilter_1/volFeBlock_2 overlapping cave/Tunnel_1/VTI18_1 ovlp=3.38325
 = Overlap ov00002: cave/Detector_0/volMuFilter_1/volFeBlock_1 overlapping cave/Tunnel_1/VTI18_1 ovlp=3.20595
 = Overlap ov00003: cave/Detector_0/volMuFilter_1/volFeBlock_0 overlapping cave/Tunnel_1/VTI18_1 ovlp=3.02865
 = Overlap ov00004: cave/Detector_0/volMuFilter_1/volMuUpstreamDet_3_5/volMuUpstreamBar_23000 overlapping cave/Tunnel_1/VTI18_1 ovlp=2.56216
 = Overlap ov00005: cave/Detector_0/volMuFilter_1/volMuUpstreamDet_2_4/volMuUpstreamBar_22000 overlapping cave/Tunnel_1/VTI18_1 ovlp=2.38487
 = Overlap ov00006: cave/Detector_0/volMuFilter_1/volMuUpstreamDet_1_3/volMuUpstreamBar_21000 overlapping cave/Tunnel_1/VTI18_1 ovlp=2.20757
 = Overlap ov00007: cave/Detector_0/volMuFilter_1/volMuUpstreamDet_0_2/volMuUpstreamBar_20000 overlapping cave/Tunnel_1/VTI18_1 ovlp=2.03027
 = Overlap ov00008: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_3_10/volMuDownstreamBar_ver_33060 overlapping cave/Tunnel_1/VTI18_1 ovlp=2.02166
 = Overlap ov00009: cave/Detector_0/volVeto_1/volVetoPlane_0_0/volVetoBar_10000 overlapping cave/Tunnel_1/VTI18_1 ovlp=1.21925
 = Overlap ov00010: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_3_10/volMuDownstreamBar_ver_33061 overlapping cave/Tunnel_1/VTI18_1 ovlp=1.19526
 = Overlap ov00011: cave/Detector_0/volMuFilter_1/volFeBlock_4 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.78711
 = Overlap ov00012: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30060 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.39433
 = Overlap ov00013: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30061 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.378716
 = Overlap ov00014: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_3_10/volMuDownstreamBar_ver_33062 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.370365
 = Overlap ov00015: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30062 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.363102
 = Overlap ov00016: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30063 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.347488
 = Overlap ov00017: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30064 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.331874
 = Overlap ov00018: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30065 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.316261
 = Overlap ov00019: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30066 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.300647
 = Overlap ov00020: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30067 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.285033
 = Overlap ov00021: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30068 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.269419
 = Overlap ov00022: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30069 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.253805
 = Overlap ov00023: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30070 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.238192
 = Overlap ov00024: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30071 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.222578
 = Overlap ov00025: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30072 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.206964
 = Overlap ov00026: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30073 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.19135
 = Overlap ov00027: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30074 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.175737
 = Overlap ov00028: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_2_9/volMuDownstreamBar_ver_32060 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.161609
 = Overlap ov00029: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30075 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.160123
 = Overlap ov00030: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30076 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.144509
 = Overlap ov00031: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30077 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.128895
 = Overlap ov00032: cave/Detector_0/volMuFilter_1/volMuDownstreamDet_0_7/volMuDownstreamBar_ver_30078 overlapping cave/Tunnel_1/VTI18_1 ovlp=0.113281

### CODE REVIEW

**Comment by ThomasRuf** [comment]
Just an observation, EmulsionDet.BrPackX(Y) changed significantly from 0.6cm to 0.1cm. What is the reason?

**Comment by antonioiuliano2** [comment]
Hi Thomas,
I have updated it according to the wall box information I received along
with the wall positions .

In one x/y direction, The emulsion size is 19.2 cm, the package is (2*0.05
cm, both sides). Therefore the whole inner length/height is
 (0.05 + 19.2 + 0.05) cm + (0.05 +19.2 + 0.05) cm = 38.6 cm

So, this matches the inner size of the wall box: 38.6 x 38.6 cm^2

Best regards,
Antonio

Il giorno mar 23 nov 2021 alle ore 10:34 Thomas Ruf <
***@***.***> ha scritto:

**Comment by ThomasRuf** [comment]
OK. Another question. From where did you get: Scifi.xdim = 39.0 * u.cm #sensitive only
Within ~100microns, it is probably correct, but 39cm is an approximation. But probably doesn't matter, since it is used only for passive material, CarbonFibreVolume.

**Comment by antonioiuliano2** [comment]
Dear Thomas,
I got these drawings from Ettore. Looking at the red table with the
channels.
A has x = -195.28 mm and it goes all the way up to x = 195.92 at the end.
The accurate distance would be thus 39.12 *u.cm.
Similar table is provided for the ydim.

Best regards,
Antonio

Il giorno mar 23 nov 2021 alle ore 11:06 Thomas Ruf <
***@***.***> ha scritto:

**Comment by ThomasRuf** [comment]
yes, I know the table. But it only gives the position of the first channel. Second, it might not reflect the size of the detector. The first channel does not start with the edge of the board.

**Comment by ThomasRuf** [comment]
Another question: Did you modified 
c.MuFilter.VetozC = c.EmulsionDet.zC - c.EmulsionDet.zdim/2. - (c.MuFilter.NVetoPlanes * c.MuFilter.VetoPlaneZ)/2. to 

c.MuFilter.VetozC = 288.89 *u.cm - (c.MuFilter.NVetoPlanes * c.MuFilter.VetoPlaneZ)/2.

**Comment by ThomasRuf** [comment]
Just checking. Did you (antonioiuliano2) modified anything concerning Scifi? I trying to update NewGeometry2 with the changes of the master branch.

**Comment by antonioiuliano2** [comment]
Yes, I changed the general positions of the scifi volumes, otherwise they
would have overlapped with the wall boxes.


Il giorno mar 23 nov 2021 alle ore 11:46 Thomas Ruf <
***@***.***> ha scritto:

**Comment by ThomasRuf** [comment]
sorry, I meant changes to the c++ code, Scifi.cxx?

**Comment by antonioiuliano2** [comment]
Yes, I am referring to those.

Il giorno mar 23 nov 2021 alle ore 11:56 Thomas Ruf <
***@***.***> ha scritto:

**Comment by ThomasRuf** [comment]
OK, I see, you added dx_survey ... as in EmulsionDet.cxx.  I will move this to the config file, with the new framework of exchanging parameters between python and c++, this will not require any new set methods.

**Comment by ThomasRuf** [comment]
(Un)fortunately the geometry of the Scifi changed enormously, might be a bit more work now to implement the new positions.

**Comment by ThomasRuf** [comment]
Could you (antonioiuliano2) have a quick look at Scifi.cxx in the master branch, maybe you see a quick way of introducing the survey positions. Having some problem with with dx and dzborder.

**Pull request merged**
