### PR TITLE
Update shipLHC CMake for new shipdist

### PR DESCRIPTION
**Pull request by olantwin**
To synchronise to the changes in #4

### CODE REVIEW

**Review by antonioiuliano2 — APPROVED** [review]
Thank you, now it seems all fine to me

**Comment by olantwin** [comment]
BTW, you and other @SND-LHC/core-developers should now have write access to this repo and snddist.

I suggest we still use pull requests as much as possible though to prevent making silly mistakes and at least a second pair of eyes on changes (although it's always possible to override if necessary).

**Comment by ThomasRuf** [comment]
Hallo Oliver,
in case, I want to work with the existing stack of SHiPBuild on my local machine which I use for FairShip master.
I do git clone https://github.com/SND-LHC/sndsw
and then, what is next? Haven't figured out what recipe to use to build sndsw.

**Comment by antonioiuliano2** [comment]
Hi Thomas, 
as discussed in issue #5. currently it is still built from shipdist, just like fairship. We still need to separate the recipes 
On my local machine, I consider sndsw just as a separate FairShip branch:

git remote add sndlhc https://github.com/SND-LHC/sndsw/
git checkout -b sndlhc sndlhc/master
FairShip/aliBuild.sh 

Best regards,
Antonio

**Comment by ThomasRuf** [comment]
OK. I will try.

**Comment by olantwin** [comment]
Essentially we'd need to add a recipe to snddist for sndsw, as aliBuild expects the repositories or directories to be the same as the package name.

I'll do that today.

But Antonio's workaround works and should continue to work for the time being.

**Comment by ThomasRuf** [comment]
Don't have much success with the workaround. Failing with  git checkout -b sndlhc sndlhc/master -> fatal: 'sndlhc/master' is not a commit and a branch 'sndlhc' cannot be created from it.

**Comment by olantwin** [comment]
There now is a recipe for sndsw in snddist. You should be able to use it with `$ALIBUILD/alibuild build sndsw -c snddist`

**Comment by olantwin** [comment]
> Don't have much success with the workaround. Failing with git checkout -b sndlhc sndlhc/master -> fatal: 'sndlhc/master' is not a commit and a branch 'sndlhc' cannot be created from it.

Could you try `git fetch sndlhc` and then `git checkout sndlhc/master` and `git branch snd`? Then you should be left with a branch `snd` which should be up to date with this repository.

**Comment by ThomasRuf** [comment]
I cloned snddist and sndsw.  Trying alibuild/aliBuild build sndsw -c snddist
usage: aliBuild [-h] [-d] [-n] {analytics,architecture,build,clean,deps,doctor,init,version} ...
aliBuild: error: Default `release' does not exists. Viable options:

**Comment by ThomasRuf** [comment]
i think I get now confused with sndlhc and sndsw.

**Comment by olantwin** [comment]
Sorry, I made a typo. This is fixed in <https://github.com/SND-LHC/snddist/commit/b136ac18ce7269958eaa5ca1891803c486d55565>

**Comment by olantwin** [comment]
> i think I get now confused with sndlhc and sndsw.

sndlhc is just what Antonio called his remote. This can be freely renamed.

**Comment by ThomasRuf** [comment]
alibuild/aliBuild build sndsw -c snddist  does now work. HOWEVER, it wants to build the full stack, from alpaca to ROOT/Geant4...FairRoot, which is not so good. Had hoped it could use what had already been compiled for FairShip.

**Comment by ThomasRuf** [comment]
Antonio's approach suffers from the same problem. There, it also wants to recompile the whole world. 

Tried with setting up environment for existing FairShip, and then use the option --always-prefer-system. This helped a bit, it reuses GEANT4, GENIE, ... but does not help for others, FairRoot, ROOT, fmt, FairLogger, XRootD, ...

**Comment by ThomasRuf** [comment]
When building sndsw with snddist, I fail with lhapdf
++ curl -L https://lhapdfsets.web.cern.ch/lhapdfsets/current/cteq6l1.tar.gz
I thought this had been fixed for FairShip. Am I wrong?

**Comment by olantwin** [comment]
I'll need to check whether snddist is completely up to date. It should be essentially the same as the latest defaults-fairship.sh. Maybe I forgot some instances where I need to rename things?

Could we please discuss this in an issue of the snddist repository?

**Comment by olantwin** [comment]
> alibuild/aliBuild build sndsw -c snddist does now work. HOWEVER, it wants to build the full stack, from alpaca to ROOT/Geant4...FairRoot, which is not so good. Had hoped it could use what had already been compiled for FairShip.

That's one of the sideeffects of the defaults being renamed, I suspect. I think reusing builds accross defaults is not possible. `--always-prefer-system` should work in principle.

**Comment by ThomasRuf** [comment]
--always-prefer-system works only after some boot strapping with a handmade setup script on cvmfs defining the environment variable for finding the libraries.
Need to check what could be the recipe to use it on a local machine.

in any case, we need to come up with a recipe for not so experienced users.

**Comment by olantwin** [comment]
Yes, the whole CVMFS stuff we need to figure out. For now, I first wanted to make sure the regular aliBuild recipes are in place.

As we discussed in the past, --always-prefer-system of course won't work for local machines unless they are very similar to lxplus7 and have access to CVMFS (even for FairShip).

I'll also add instructions etc. to the readmes over the following days.

**Comment by olantwin** [comment]
However, on lxplus7, we should be able to use `--always-prefer-system` with SHiP's CVMFS for now, if I'm not mistaken. I haven't had time to try it yet though.

**Comment by antonioiuliano2** [comment]
At the moment, on lxplus I am working on this repository still by using:

source /cvmfs/ship.cern.ch/SHiP-2021/latest/setUp.sh
$ALIBUILD/aliBuild build FairShip --default fairship --always-prefer-system
--config-dir $SHIPDIST

What should the updated commands be for the new recipe?

Best regards,
Antonio

Il giorno lun 7 dic 2020 alle ore 17:07 Oliver Lantwin <
notifications@github.com> ha scritto:

**Comment by olantwin** [comment]
This works for me:

```bash
source /cvmfs/ship.cern.ch/SHiP-2021/latest/setUp.sh
git clone https://github.com/SND-LHC/snddist
$ALIBUILD/aliBuild build sndsw -c snddist --always-prefer-system
```

**Comment by olantwin** [comment]
And additionally `$ALIBUILD/aliBuild init -c snddist sndsw` for a development version of `sndsw`.

**Comment by ThomasRuf** [comment]
What is meant with a development version? What does  aliBuild init require?

**Comment by olantwin** [comment]
A development version is aliBuild's jargon for a local modifiable copy of a package, i.e. a clone of the packages git repo in the working directory.

`aliBuild init` is the aliBuild way of setting this up (it essentially clones the package and checks out the correct branch/tag)

The benefits are that we don't have to manually clone two github repositories to set up things (but only snddist), and stick more closely with how aliBuild is designed to be used.

`aliBuild init` requires only `aliBuild` and an internet connection. Maybe I misunderstand the question.

**Pull request merged**
