### PR TITLE
Remove duplicate copies of ShipUnit.h

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Comment by olantwin** [comment]
@ThomasRuf Maybe also worth doing in FairShip? (or maybe doing there and then just reusing it here)

**Review by ThomasRuf — COMMENTED** [review]
I think for this to work, the CMakeLists.txt in the other directories need to contain the include path to shipdata.

**Comment by olantwin** [comment]
I think every sub-directory already includes shipdata in it's `CMakeLists.txt`.

Maybe we should create a new directory where we keep headers needed by almost all files?

**Review by ThomasRuf — APPROVED** [review]
i think this was a bit the idea of shipdata.

**Comment by olantwin** [comment]
Then that's perfect. I think I'll create a pull request to FairShip first though, to deduplicate the files there, and then this pull request can simply be updated to use the `shipdata` version.

**Pull request merged**
