### PR TITLE
Some cleanup of old files

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Review by antonioiuliano2 — COMMENTED** [review]
Thank you for your changes. I have just a question:
since you removed aliBuild.sh, my temporary workaround on the laptop (as a FairShip fork) will not work anymore. 

Have you found a way to use built packages from FairShip, or will I now need to have two copies of every package (ROOT, Geant4, etc.)? Unfortunately I work from Ubuntu 20, now Scientific Linux, therefore the --always-prefer-system approach you were discussing before will not work for me.

**Review by ThomasRuf — COMMENTED** [review]
maybe alibuild can be adjusted for SND?

**Comment by olantwin** [comment]
You can still use `shipdist` and `defaults-fairship.sh` to build `sndsw` as a fork of FairShip. packages should be reused in this case.

The reason the packages are rebuilt with `sndsw` is due to the renaming of the `default`.

**Comment by olantwin** [comment]
> maybe alibuild can be adjusted for SND?

Could you elaborate? AliBuild works fine for SND, the only issue is that aliBuild's caching doesn't reuse packages between different defaults (which makes sens generally, as one can then have e.g. debug packages as release packages built at the same time and can use either by selecting a different default when using `alienv enter`

**Comment by ThomasRuf** [comment]
alibuild.sh was written for people not working with alibuild all the day. one script, easy to remember. I myself always have problem to remember the right syntax for alibuild build ... , alidoctor, alienv.

**Comment by antonioiuliano2** [comment]
> maybe alibuild can be adjusted for SND?

I guess Thomas is talking about aliBuild.sh script.

**Comment by olantwin** [comment]
> alibuild.sh was written for people not working with alibuild all the day. one script, easy to remember. I myself always have problem to remember the right syntax for alibuild build ... , alidoctor, alienv.

In my opinion, it would better to not hide aliBuild behind a script. In the normal use-case it's just a pair of commands the users will need to know:

`aliBuild build sndsw` and `alienv enter sndsw`, which I think is not unreasonable (compared to e.g. all the lb-env commands on the LHCb side for example). The tool is also well-documented.

While when everything works fine `alibuild.sh` indeed saves one command, if somethings breaks for any reason, there is one additional level of abstraction making it harder to troubleshoot.

While we should of course try to reduce unnecessary complexity, I think here I prefer a little added complexity (and flexibility) over having a black-box script that works in 99% of the cases, but complicates troubleshooting if something goes wrong.

**Comment by olantwin** [comment]
Also, on lxplus we ask users to use `aliBuild` and `alienv` directly anyway, so using them directly locally makes sure that the procedures are as similar as possible.

Otherwise we have `aliBuild`, `alienv` etc. + `alibuild.sh`, which only adds complexity.

**Comment by olantwin** [comment]
@antonioiuliano2 Any views on this? As we use `aliBuild` directly on `lxplus` anyway, I am inclined to merge this as initially proposed.

**Comment by antonioiuliano2** [comment]
I am sorry Oliver, but I actually agree with Thomas on this one.

On lxplus we "use" aliBuild only to load CVFMS packages, so the user's knowledge requirement is minimal.
On a local machine instead, we need to install a lot of packages, or check if they can be taken from the system,  and aliDoctor provides a great help.

With this script, it is enough to call aliBuild.sh --debug (or anything else, I just use --debug as a reminder), and aliDoctor will automatically be called and check if you can install the packages. 

Without it, you need to know how to call aliDoctor, and in the Readme you at the momento only menioned the existence of aliDoctor itself, without the required command to launch it (I know it is similar to the alibuild one, but a new user does not know it).

So, before confirming the removal of aliBuild.sh, we should at least make sure that the user knows all the commands which this script provided.

**Comment by olantwin** [comment]
I agree that we should document how to use `alilDoctor` to troubleshoot. I will do that.

The main things I want to achieve are the following:
- Use one set of commands on lxplus and locally
-  Force the user to learn as few commands as possible
- Minimise our maintenance load

Now there are two ways forward:
- Use aliBuild and co everywhere (this would be my preferred solution, but, as you point out, this needs to be documented well, and pointing to the ALICE documentation is insufficient)
  - One step to make this simpler was to swtich to using `defaults-release.sh`, as this reduces the number of command line arguments used, so that the normal user doesn't need to know what a "default" is
- Use our own setup script everywhere (this would require some development effort, and preferable would not be named `aliBuild.sh` so people don't confuse it with `aliBuild`)

**Review by antonioiuliano2 — APPROVED** [review]
I agree to remove aliBuild.sh if all the alibuild commands (including aliDoctor) will be documented in the Readme.

**Comment by olantwin** [comment]
OK, I will try to streamline the `README` in a separate pull request and will then return to this one once we are happy.

**Comment by olantwin** [comment]
With #30 now done, I will go ahead and merge this.

**Pull request merged**
