### PR TITLE
second round for sndlhc event header class - this time based on FairE…

### PR DESCRIPTION
**Pull request by siilieva**
…ventHeader, not inheriting from it.

### CODE REVIEW

**Review by ThomasRuf — APPROVED** [review]
Let us try it

**Comment by ThomasRuf** [comment]
I can now read back the event time in python! Great!

**Comment by ThomasRuf** [comment]
there is an issue when running  in online mode. Can it be that you expect a different run_timestamps.json?
unfortunately, there is no further information, except that it happens in run.init()
  File "/home/sndmonitoring/SNDBuild/sw/slc8_x86-64/sndsw/master-local1/shipLHC/rawData/ConvRawData.py", line 107, in Init
    self.run.Init()
cppyy.gbl.nlohmann.detail.parse_error: void FairRunAna::Init() =>
    parse_error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

more /mnt/raid1/data_online/run_004763/run_timestamps.json 
{"start_time":"2022-08-12T15:10:33Z"}

**Comment by siilieva** [comment]
or cpp conversion doesn't know how to read from the server. Is this online (-M) or auto (-a) mode?

**Comment by ThomasRuf** [comment]
auto mode on the monitor VM. 
python -i $SNDSW_ROOT/shipLHC/scripts/run_Monitoring.py --server=root://snd-server-1.cern.ch/ -p /mnt/raid1/data_online/ -g ../geofile_sndlhc_TI18_V2_12July2022.root   -A --ScifiResUnbiased 1 --Nlast 1000 --Nupdate 1000 -cpp
Server is specified in the options,

**Comment by ThomasRuf** [comment]
There is a small subtlety, since yesterday. The data file is in 
/mnt/raid1/data_online/monitoring_run_004763/data_xxxx.root   xxxx = partition

 while the json file is in
/mnt/raid1/data_online/run_004763/

**Comment by siilieva** [comment]
ok, and where is the board_mapping.json?

**Comment by ThomasRuf** [comment]
all additional info is in /mnt/raid1/data_online/run_004763/, only the data file is in /mnt/raid1/data_online/monitoring_run_004763/

**Comment by siilieva** [comment]
got it, and the structure of raw-data on EOS remains the same?

**Comment by ThomasRuf** [comment]
nothing changes for EOS. Also, this special location is only used when the option slowStream is set. Not sure why you need to know this, I thought I steer this from run_Monitoring. Something I must have overlooked.

**Comment by siilieva** [comment]
it is only that the cpp conversion assumes a single path to the *.json and data_X.root files. Perhaps it is best to pass the JSON files as input objects to cpp conversion to avoid any mismatches.

**Comment by siilieva** [comment]
> it is only that the cpp conversion assumes a single path to the *.json and data_X.root files. Perhaps it is best to pass the JSON files as input objects to cpp conversion to avoid any mismatches.

-- better pass the string of the path_to_JSON_files

**Comment by ThomasRuf** [comment]
yes, this is a good idea. I have to leave now, let me know if I have to change/add something. Have a nice weekend.

**Comment by siilieva** [comment]
for completeness of this discussion: discussed-here issues are addressed with the pull request https://github.com/SND-LHC/sndsw/pull/125/files

**Pull request merged**
