### PR TITLE
Create GitHub actions

### PR DESCRIPTION
**Pull request by antonioiuliano2**
Following @olantwin advice,
I created an automated GitHub Action, to update the Doxygen documentation whenever there is a new push to the master branch of our code.

For the Doxygen configuration file, please see my previous pull request.

Best Regards,
Antonio

### CODE REVIEW

**Review by olantwin — APPROVED** [review]
Looks good to me :)

For reference, [this](https://github.com/marketplace/actions/doxygen-github-pages-deploy-action) is the action used.

**Comment by antonioiuliano2** [comment]
Thank you Thomas,

I can see that the action is already active, and the gh-pages branch has
been created correctly:

SND-LHC/sndsw at gh-pages (github.com)
<https://github.com/SND-LHC/sndsw/tree/gh-pages>

Could you please set this branch as the github pages reference branch, so
the page is deployed?

It is done from the settings, like this (see attached screenshot from my
fork).

I cannot do that myself, since I am not the maintainer of the repository.

Best Regards,
Antonio



Il giorno sab 30 lug 2022 alle ore 09:41 Thomas Ruf <
***@***.***> ha scritto:

**Comment by antonioiuliano2** [comment]
Ok, did this:
***@***.***
Is there anything else to do? Save?

Von: Antonio Iuliano ***@***.***>
Gesendet: Saturday, 30 July 2022 10:11
An: SND-LHC/sndsw ***@***.***>
Cc: SND-LHC/sndsw ***@***.***>; Author ***@***.***>; Thomas Ruf ***@***.***>; Oliver Lantwin ***@***.***>
Betreff: Re: [SND-LHC/sndsw] Create GitHub actions (PR #120)

Thank you Thomas,

I can see that the action is already active, and the gh-pages branch has been created correctly:

SND-LHC/sndsw at gh-pages (github.com)<https://github.com/SND-LHC/sndsw/tree/gh-pages>

Could you please set this branch as the github pages reference branch, so the page is deployed?

It is done from the settings, like this (see attached screenshot from my fork).

I cannot do that myself, since I am not the maintainer of the repository.

Best Regards,
Antonio



Il giorno sab 30 lug 2022 alle ore 09:41 Thomas Ruf ***@***.******@***.***>> ha scritto:

Merged #120<https://github.com/SND-LHC/sndsw/pull/120> into master.

**Comment by antonioiuliano2** [comment]
Thank you,

That is correct. You just need to set it as it says (branch gh-pages,
/(root) ) and click on Save.

Right now it is trying to read the pages from a docs folder, which does not
exist.

Thank you very much!
Antonio

Il giorno sab 30 lug 2022 alle ore 10:29 Thomas Ruf ***@***.***> ha
scritto:

**Comment by antonioiuliano2** [comment]
Dear Thomas,

I can confirm that the web page is now accessible:
SND Software: SNDSW Class Reference (snd-lhc.github.io)
<https://snd-lhc.github.io/sndsw/>

It should be now synchronized automatically at every push on the sndsw
master branch.
Thank you very much!
Best regards,
Antonio

Il giorno sab 30 lug 2022 alle ore 10:40 antonio iuliano <
***@***.***> ha scritto:

**Pull request merged**
