### PR TITLE
Tracking updates

### PR DESCRIPTION
**Pull request by siilieva**
- introduce masking of DS planes in SndlhcTracking's DStrack - might not be the best python coding
 - put messages of SndlhcMuonReco to FairLogger
 - running MC with the run_TrackSelector (for efficiency studies it is useful to copy the full input into the output root file)
 - track velocity in sndRecoTask obtained from 1/v fit

### CODE REVIEW

**Comment by ThomasRuf** [comment]
What is the reason for the modification of Monitor.py?
DS clusters, are they made accessible to the user, with links back to the hits?

**Comment by siilieva** [comment]
> What is the reason for the modification of Monitor.py? 
Only changed the MC part of Monitor.py to have all input events into the output, regardless if a track is fit or not. This is useful for making checks of cases when tracking failed, also to calculate tracking efficiency in MC.
>DS clusters, are they made accessible to the user, with links back to the hits?
What does it mean with links back to the hits?
What I did is pass the DS cluster container to the output. No modifications of how DS clusters are formed. Digi hits (Scifi and MuFilter ones) are dumped to output too as usual.

**Comment by siilieva** [comment]
just pulled newest master and did rebase

**Review by ThomasRuf — APPROVED** [review]
ok

**Pull request merged**
