### PR TITLE
Changing detector position along x and updating target composition

### PR DESCRIPTION
**Pull request by antonioiuliano2**
Dear all,

this large pull request contains a main update of the geometry, according to the discussions of the last days. The main changes are:

- The position of the detector, now set at negative x after the discussion with @ThomasRuf  and @abuonaura. Consequently, the floor position is reflected with respect to the x axis too;

- The emulsion bricks now have less transverse size (19.2 cm x 19.2 cm instead of 41 cm x 41 cm), and are arranged in a 2 x 2 structure in the transverse view. A border of 3 mm is added at all borders, which will be filled with the brick packaging;

- The passive material in the ECC is replaced with the following tungsten alloy: W:Ni:Cu=95:3:2

I will report these changes with more details in my slides for the Collaboration Meeting.

Best regards,
Antonio

### CODE REVIEW

**Review by olantwin — APPROVED** [review]
Looks good to me!

**Review by ThomasRuf — COMMENTED** [review]
Just for my understanding, the change of EmulsionDet.EmX/Y = 41.0 * u.cm to 19.2 is quite large. Is it really shrunk or has the definition changed, full size to half size?

c.EmulsionDet.ShiftX = 8.0*u.cm -> -8.0*u.cm, it looks like you make a translation of 16cm compared to what you had before. This would not be enough. xmax = -8cm and xmin = -47cm?

**Comment by ThomasRuf** [comment]
ok, should have looked at the full history, then my first comment would have been different. Do I understand correctly that 1 piece of emulsion is replaced by 4 pieces covering roughly the same surface? No change for the scifi?

**Comment by antonioiuliano2** [comment]
> ok, should have looked at the full history, then my first comment would have been different. Do I understand correctly that 1 piece of emulsion is replaced by 4 pieces covering roughly the same surface? No change for the scifi?

Hi Thomas, that is correct. I have prepared some displays to show the updated geometry. You can find them here:
https://cernbox.cern.ch/index.php/s/yYcoFWBi51e75PU

**Comment by antonioiuliano2** [comment]
> Just for my understanding, the change of EmulsionDet.EmX/Y = 41.0 * u.cm to 19.2 is quite large. Is it really shrunk or has the definition changed, full size to half size?
> 
> c.EmulsionDet.ShiftX = 8.0_u.cm -> -8.0_u.cm, it looks like you make a translation of 16cm compared to what you had before. This would not be enough. xmax = -8cm and xmin = -47cm?

I have also changed the position of the volume in the source code, EmulsionDet.cxx:
top->AddNode(volTarget,1,new TGeoTranslation(ShiftX-XDimension/2,ShiftY+YDimension/2,fCenterZ));

instead of 

top->AddNode(volTarget,1,new TGeoTranslation(ShiftX+XDimension/2,ShiftY+YDimension/2,fCenterZ));

This way, it starts at -8 cm and it continues along negative x. Checking with getGeoInformation:
volTarget_1                 : z=    0.0000cm  dZ=   28.4750cm  [  -28.4750      28.4750] dx=   19.8000cm [  -47.6000      -8.0000] dy=   19.8000cm [   15.5000      55.1000]                  air

**Comment by ThomasRuf** [comment]
ok, then i agree with the modifications. How do I make an approval?

**Comment by antonioiuliano2** [comment]
I think the problem is that the variables c.EmulsionDet.ShiftX = 8.0*u.cm and c.EmulsionDet.ShiftY = 15.5*u.cm are ill-defined, since they refer to an edge of the target, instead of its center like it is usually done. Would you agree to be better if I change them?

**Comment by antonioiuliano2** [comment]
> ok, then i agree with the modifications. How do I make an approval?

Sorry, I have read your message only after posting mine. Anyway, you can accept modifications from the "Add your review" section, by clicking on the green button "Review changes" and you click on "Accept"

**Comment by ThomasRuf** [comment]
This might be a good idea, less confusion. But what would be a better name? minX is also confusing. At the end it is the lower left corner looking in "beam" direction, correct? In LHCb, we had avoided left and right, since it depends on the view direction. We called it A and C, don't remember why. Or a the SPS, Jura and Salve side.

**Review by ThomasRuf — APPROVED** [review]

**Comment by ThomasRuf** [comment]
OK, done. Thanks to your clear description, without the hint about the files changed tab, I would have not found it.

**Comment by antonioiuliano2** [comment]
> This might be a good idea, less confusion. But what would be a better name? minX is also confusing. At the end it is the lower left corner looking in "beam" direction, correct? In LHCb, we had avoided left and right, since it depends on the view direction. We called it A and C, don't remember why. Or a the SPS, Jura and Salve side.

The less ambiguous way is to always refer to the center when defining the positions (it is the way SHiP positions in the geometry files are usually defined too). So I solved this issue by changing shift variables like this:

c.EmulsionDet.ShiftX = -8.0*u.cm - c.EmulsionDet.xdim/2.
c.EmulsionDet.ShiftY = 15.5*u.cm + c.EmulsionDet.ydim/2.

and then the AddNode in EmulsionDet.cxx calls simply becomes:
top->AddNode(volTarget,1,new TGeoTranslation(ShiftX,ShiftY,fCenterZ));

This way, all information is stored in the geometry file, and it is a lot clearer.

**Review by olantwin — APPROVED** [review]
I agree that the shift of the centre is much easier to understand. Thanks for the update!

**Review by ThomasRuf — APPROVED** [review]

**Pull request merged**
