### PR TITLE
adding new functionalities

### PR DESCRIPTION
**Pull request by ThomasRuf**
Commit contains the following new features:

for a magnified display (using zoom) it is useful to switch off drawing the detector, use: withDetector = False
implement user hook for a processing of the event after display. For example useful if user wants to display special objects.
add option with2Points. The normal display only plots one end point of a fibre or bar. But since the fibres and bars are not aligned with the X- and Y-axis of the physics coordinate system, the true position in X(Y) could vary with the actual position in Y(X) by a few mm. With with2Points=True, both end points are drawn.
eventComment dictionary. Adds the possibility to add a comment to the event after display. Instead of typing q for next event, add comment as plain text. Can be accessed later and eventually saved or printed.

### CODE REVIEW

**Comment by olantwin** [comment]
Would you mind if I split this into one commit per added functionality? Then I'll also add your explanation to each commit message.

Note that this should be merged before #190 (which then needs to be rebased).

I already had a look at the commit yesterday and it looks good to me otherwise.

**Comment by ThomasRuf** [comment]
I have no problem with this, please go ahead.

**Comment by olantwin** [comment]
Ok, I'll try to do it before lunch and then update the pull request here.

**Comment by olantwin** [comment]
Made a new branch and PR to not overwrite your changes: #191

**Pull request closed without merging**
