### PR TITLE
Truf/tracking options

### PR DESCRIPTION
**Pull request by ThomasRuf**
After several email exchanges with Antonia, received now the position of the floor according to the measurements of Antonio. Need to move the floor by -3.5cm relative to the FLUKA position. 
Also added now rock all around the tunnel.

### CODE REVIEW

**Comment by ThomasRuf** [comment]
sorry, all too complicated for me. I have a working version, no idea how to upload it without conflicts.

**Comment by olantwin** [comment]
The problem is that 806731f is included again.

You should be able to do `git rebase master`. Most likely git notices by itself, that that commit is already in master and just skips it.

If not, you can use `git rebase -i master` and select only the commits you want to include in this pull request.

**Comment by ThomasRuf** [comment]
git rebase master
Aktueller Branch truf/trackingOptions ist auf dem neuesten Stand.
and now?

**Comment by olantwin** [comment]
Could you do `git fetch`? It seems your local version of master might not be up to date.

**Comment by ThomasRuf** [comment]
git fetch
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Total 20 (delta 10), reused 10 (delta 10), pack-reused 10
Entpacke Objekte: 100% (20/20), 11.34 KiB | 504.00 KiB/s, Fertig.
Von https://github.com/SND-LHC/sndsw
 * [neuer Branch]    aiuliano/makeSNDGenieEvents -> origin/aiuliano/makeSNDGenieEvents
   2a7eabc..d9e454f  master                      -> origin/master

and then?

**Comment by olantwin** [comment]
Now repeat my previous instructions. With the old master-branch rebasing was a no-op, as your changes were already fully updated with the outdated master branch.

**Comment by ThomasRuf** [comment]
git rebase master
Aktueller Branch truf/trackingOptions ist auf dem neuesten Stand.
??
git rebase -i master 
  GNU nano 4.8                                             /media/disk0/SNDBuild/mess/sndsw/.git/rebase-merge/git-rebase-todo                                                        
pick 806731f add all tracking options to Floor
pick 8347a0e move floor by -3.5cm to match with measurements, add rock all around the tunnel
pick 1ad0e86 using alternative way of accessing global objects, the ROOT way stopped working

then comes a lot of text. No idea what to do.

I think I go back to my old system. do a git clone, copy my changes to this clone, do new branch, do commit, do push, start pull request. It is a bit painful. Maybe tomorrow.

**Comment by olantwin** [comment]
> git rebase master
> Aktueller Branch truf/trackingOptions ist auf dem neuesten Stand.
> ??
> git rebase -i master
> GNU nano 4.8 /media/disk0/SNDBuild/mess/sndsw/.git/rebase-merge/git-rebase-todo
> pick [806731f](https://github.com/SND-LHC/sndsw/commit/806731f4a1e9e789dbab10173de6b886fbb71761) add all tracking options to Floor
> pick [8347a0e](https://github.com/SND-LHC/sndsw/commit/8347a0e8b3f07f22b6501888121e0b7ac8694a6d) move floor by -3.5cm to match with measurements, add rock all around the tunnel
> pick [1ad0e86](https://github.com/SND-LHC/sndsw/commit/1ad0e866dc2451e8e06a6b02812426f8c7cee0ed) using alternative way of accessing global objects, the ROOT way stopped working
> 
> then comes a lot of text. No idea what to do.
> 
> I think I go back to my old system. do a git clone, copy my changes to this clone, do new branch, do commit, do push, start pull request. It is a bit painful. Maybe tomorrow.

Now you just need to remove the line 
```
pick 806731f add all tracking options to Floor
```
, save the file and it should work.

You then only need to force push to this branch again.

**Comment by ThomasRuf** [comment]
git rebase -i master

OK, removed the line you mentioned. Saved file.

automatischer Merge von shipLHC/Floor.h
KONFLIKT (Inhalt): Merge-Konflikt in shipLHC/Floor.h
automatischer Merge von shipLHC/Floor.cxx
KONFLIKT (Inhalt): Merge-Konflikt in shipLHC/Floor.cxx
automatischer Merge von macro/run_simScript.py
KONFLIKT (Inhalt): Merge-Konflikt in macro/run_simScript.py
error: Konnte 8347a0e... (move floor by -3.5cm to match with measurements, add rock all around the tunnel) nicht anwenden
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Konnte 8347a0e... (move floor by -3.5cm to match with measurements, add rock all around the tunnel) nicht anwenden

ubuntu:/media/disk0/SNDBuild/mess/sndsw>git push
fatal: Sie befinden sich im Moment auf keinem Branch.
Um die Historie, führend zum aktuellen (losgelöster HEAD)
Status zu versenden, benutzen Sie

    git push origin HEAD:<Name-des-Remote-Branches>

This is going nowhere.

**Comment by olantwin** [comment]
Ah, I see what the issue is now.

Sorry for the mistake:

1. `git rebase --abort`
2. `git rebase -i origin/master`
3. delete the line
4. `git push -f`

**Comment by olantwin** [comment]
Explanation: with `git fetch`, only `origin/master` is updated, not `master`.

**Comment by ThomasRuf** [comment]
too late. deleted everything.

**Comment by olantwin** [comment]
I rebased the branch. Now it is up to date with the changes to master. Now it should be mergeable. Either as a new PR or reopening this one.

**Comment by olantwin** [comment]
Superseded by #47

**Pull request closed without merging**
