### PR TITLE
Improve CMakeLists for sndsw genie-dependent apps

### PR DESCRIPTION
**Pull request by cvilelahep**
Successfully builds with:
 - `Mar10` snddist release on centos7
 - `June10` snddist release on centos7
 - `June26` snddist release on centos8

### CODE REVIEW

**Review by ThomasRuf — APPROVED** [review]

**Comment by ThomasRuf** [comment]
On lxplus7 with June 10, it works.

On Ubuntu 20.04 with snddist master, it does not work.  [shipgen/CMakeFiles/sndlhcGSimpleNtpConverter.dir/build.make:103: bin/sndlhcGSimpleNtpConverter] Error 1

which is surprising to me.

**Comment by ThomasRuf** [comment]
if I look at the first undefined reference:
/usr/bin/ld: /home/trufsnd/SNDBUILD/sw/ubuntu2004_x86-64/GENIE/v3.2.0-local3/lib/libGTlFlx.so: undefined reference to `genie::PDGLibrary::Find(int, bool)'

it is defined in 
nm /home/trufsnd/SNDBUILD/sw/ubuntu2004_x86-64/GENIE/v3.2.0-local3/lib/libGFwParDat.so | grep PDGLibrary | grep Find
000000000000a1c0 T _ZN5genie10PDGLibrary4FindEib
00000000000081a0 t _ZN5genie10PDGLibrary4FindEib.cold

the lib appears in target_link, even before libGTlFlx.so
target_link_libraries(sndlhcGSimpleNtpConverter -L$ENV{GENIE_ROOT}/lib/ -lGFwMsg -lGFwReg -lGFwAlg -lGFwInt -lGFwGHEP -lGFwNum -lGFwUtl -lGFwParDat -lGFwEG -lGFwNtp -lGTlFlx ${ROOT_LIBRARIES} -lEGPythia6 -L$ENV{LIBXML2_ROOT}/lib -lxml2 -L$ENV{LOG4_ROOT}/lib -llog4cpp -L$ENV{LHAPDF_ROOT}/lib -lLHAPDF)

checked that $ENV{GENIE_ROOT}/lib points to right place.
running out of ideas.

**Comment by ThomasRuf** [comment]
by the way, why do we need main executables? It is not done like this anywhere else.

**Comment by ThomasRuf** [comment]
by changing the order of link libraries, I can minimize the list of errors to: 

sw/ubuntu2004_x86-64/pythia6/v6.4.28-ship1-local1/lib/libpythia6.so: undefined reference to `structp_'
sw/ubuntu2004_x86-64/pythia6/v6.4.28-ship1-local1/lib/libpythia6.so: undefined reference to `structm_'
sw/ubuntu2004_x86-64/pythia6/v6.4.28-ship1-local1/lib/libpythia6.so: undefined reference to `pdfset_'

libpythia6 is dragged in via libGFwNum.so and TPythia6::Instance() from ROOT EGPythia6.

in pythia-6.4.28.f we have SUBROUTINES PDFSETX, STRUCTMX, STRUCTPX. I guess, the X means that it is not used and relies on external versions.  The pythia6 library contains pdfsetx which is defined, and pdfset which is undefined. 
So, who should provide these set of subroutines?

**Comment by cvilelahep** [comment]
> in pythia-6.4.28.f we have SUBROUTINES PDFSETX, STRUCTMX, STRUCTPX. I guess, the X means that it is not used and relies on external versions. The pythia6 library contains pdfsetx which is defined, and pdfset which is undefined.
> So, who should provide these set of subroutines?
> 
I think these are defined in LHAPDF: https://root-forum.cern.ch/t/select-a-pdfset-for-pythia6-inside-root/11649/3 <https://root-forum.cern.ch/t/select-a-pdfset-for-pythia6-inside-root/11649/3>

**Comment by ThomasRuf** [comment]
yes, indeed found them in libLHAPDF. 
side observation: $ENV{LIBXML2_ROOT} is not defined

**Comment by ThomasRuf** [comment]
strange, at least for, maybe it is the desired behaviour:
message("* -L$ENV{LIBXML2_ROOT}/lib -lxml2 ")
* -L/lib -lxml2 
however omitting -L$ENV{LIBXML2_ROOT}/lib -lxml2 gives unresolved xml references. Adding only -lxml2, they appear.

**Comment by cvilelahep** [comment]
Ah I guess libxml2 is being taken from the system? That would explain why LIBXML2_ROOT is not set. But if libxml2 is in a default system location, it’s strange that we get undefined xml references.

**Comment by ThomasRuf** [comment]
found the compile and link command, in case anybody spots something wrong:

sw/BUILD/e22cb5d0764af012239ad83b13445a0b26d1b9f6/sndsw/shipgen/CMakeFiles/addAuxiliaryToGST.dir/link.txt
/usr/bin/c++ -fPIC -g -O2 -std=c++17 -O2 -Wshadow  CMakeFiles/addAuxiliaryToGST.dir/addAuxiliaryToGST.cxx.o -o ../bin/addAuxiliaryToGST   -L/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/ROOT/v6-26-02-local1/li
b  -L/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/FairRoot/v18.4.2_snd-local1/lib  -L/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/EvtGen/R01-06-00-ship-local1/lib  -Wl,-rpath,/home/trufsnd/SNDBUILD-test/s
w/ubuntu2004_x86-64/ROOT/v6-26-02-local1/lib:/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/FairRoot/v18.4.2_snd-local1/lib:/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/EvtGen/R01-06-00-ship-local1/lib -L/h
ome/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/lhapdf/v6.2.3-local1/lib -lLHAPDF -L/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/GENIE/v3.2.0-local1/lib/ -lGTlFlx -lGFwUtl -lGFwEG -lGFwMsg -lGFwReg -lGFwAlg -l
GFwInt -lGFwGHEP -lGFwNum -lGFwParDat -lGFwNtp -L/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/ROOT/v6-26-02-local1/lib -lGui -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePl
ayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -Wl,-rpath,/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/ROOT/v6-26-02-local1/lib -pthread -lm -ldl -rdynamic -lEGPyt
hia6 -lEG -L/home/trufsnd/SNDBUILD-test/sw/ubuntu2004_x86-64/log4cpp/1b9f8f7c031d6947c7468d54bc1da4b2f414558d-local1/lib -llog4cpp -L/lib -lxml2

**Pull request merged**
