### PR TITLE
Fix small SiPMs offline sw assignment. Thanks to Gui for the raw-data…

### PR DESCRIPTION
**Pull request by siilieva**
… comparisons.

### CODE REVIEW

**Comment by ThomasRuf** [comment]
if small sipms are interchanged with large sipms, wouldn't this be visible in the monitoring plot?
https://snd-lhc-monitoring.web.cern.ch/offline/run.html?file=run006667.root&lastcycle , mulfilter/signalUSVeto

**Comment by siilieva** [comment]
> if small sipms are interchanged with large sipms, wouldn't this be visible in the monitoring plot? https://snd-lhc-monitoring.web.cern.ch/offline/run.html?file=run006667.root&lastcycle , mulfilter/signalUSVeto

**Comment by ThomasRuf** [comment]
OK.  It is however used in MuFilterHit::SumOfSignals(), which is called by Mufi_monitoring. Fortunately, it only uses the sum of left and right, so, adding small and large sipms. 

looking in more detail at the MuFilterHit constructor from MuFilterPoints, it only seems to consider small sipms for the right side. Also, left and right looks like a real mess, signal right goes with earliest time left, and left signal with earliest time right. Somebody should check this code.

**Comment by siilieva** [comment]
Well, the SumOfSignals is called in the task and its result is assigned to map called _plane_, but the latter is not used further as far as I see:
https://github.com/SND-LHC/sndsw/blob/master/shipLHC/scripts/Mufi_monitoring.py#L122C12-L123
And 'sumL' and 'sumR' is a sum over large SiPMs only. Can you cross-check, when time allows?
As for the constructor out of MC points - I will look a it and make a commit to this branch. Tell me if you prefer to have a separate request for that issue.

**Review by ThomasRuf — COMMENTED** [review]
OK. Further check needed for the code in the constructor from MuFilterPoint. But this will be for a separate pull request.

**Review by ThomasRuf — APPROVED** [review]

**Pull request merged**
