### PR TITLE
Latest neutron shield version

### PR DESCRIPTION
**Pull request by dcentanni**
Neutron shield implementation in SNDSW Geometry, 4 volumes:

- Two boxes, one made of borated polyethylene within another made of PMMA (Acrylic);
- Two roofs of the same layout of the two boxes.
neutron_shield_image_YZ

### CODE REVIEW

**Review by ThomasRuf — COMMENTED** [review]
This is mainly cosmetics, but the indents look a bit chaotic, see
https://github.com/SND-LHC/sndsw/blob/7f79589c18df01ed1f86a56401d61c9ef6644f6d/shipLHC/Floor.cxx

**Comment by antonioiuliano2** [comment]
Dear Daniele and Thomas,
in FairShip we used automated formatting tools, suggested by Oliver:

* clang-format (and clang-tidy) for c++ code;
* black for python code;

There is no reason why they should not work also for sndsw code.

**Comment by dcentanni** [comment]
Thanks Antonio, I did as you suggested.

**Review by ThomasRuf — APPROVED** [review]
OK

**Pull request merged**
