### PR TITLE
Edtime

### PR DESCRIPTION
**Pull request by faalicante**
2d Event Display time info
added protection in case someone has not access to eos (not printing the time)

### CODE REVIEW

**Review by ThomasRuf — APPROVED** [review]
ok

**Review by ThomasRuf — COMMENTED** [review]
I overlooked that your code only works when working on lxplus. It will not work when working remotely with access to EOS via XROOTD. Could you please have a look at rawData/ConvRawData.py, about how to read using xrootd:

       if local:
           with open(path+'board_mapping.json') as f:
               jsonStr = f.read()
       else:
           with client.File() as f:
                f.open(server+path+"/board_mapping.json")
                status, jsonStr = f.read()

**Comment by faalicante** [comment]
Do you mean for the start time json file or even for event run folders?

**Comment by ThomasRuf** [comment]
The JSON file
________________________________

**Pull request merged**
