### PR TITLE
new TI8 tunnel geometry, floor, muonDIS and ntuple particle gun for SND

### PR DESCRIPTION
**Pull request by olantwin**
@ThomasRuf

### CODE REVIEW

**Comment by olantwin** [comment]
Supersedes https://github.com/ShipSoft/FairShip/pull/379

**Comment by olantwin** [comment]
This only seems to add the Fluka particle gun though...

**Comment by olantwin** [comment]
I expect some files were not committed.

**Comment by ThomasRuf** [comment]
why only two files?

**Comment by olantwin** [comment]
What's `git status` in your repository?

**Comment by ThomasRuf** [comment]
what should I do?

**Comment by ThomasRuf** [comment]
indeed many files are not committed. now idea why not.

**Comment by ThomasRuf** [comment]
I need to check if I really committed the correct files. I am afraid I was on a wrong branch.  I hate working in n dimension, one version is enough for me.

**Comment by ThomasRuf** [comment]
at 2pm I had something which worked. Now, I have a complete mess (as expected). I need to stop now and have a fresh look tomorrow.

**Comment by ThomasRuf** [comment]
The good news, I haven't made a mistake with files for the pull request. The error which I get is due to a modification in SciFi.cx for private use, making the tunnel wall sensitive, in order to record the incoming muons. There seems to be a problem of obtaining the volume names or node names using:
        TString* volName = (TString*)gMC->CurrentVolName();
        auto tmpnodeA = gGeoManager->FindNode(fPos.X(),fPos.Y(),fPos.Z());
        auto tmpnodeE = gGeoManager->FindNode(Pos.X(),Pos.Y(),Pos.Z());
        TString* volNameA = (TString*)tmpnodeA->GetName();
        TString* volNameE = (TString*)tmpnodeE->GetName();
         LOG(DEBUG)<<" current vol "<<volName->Data() <<"A node "<<volNameA->Data()<<"E node "<<volNameE->Data() ;
either the names printed have nothing todo with Scifi, like entering streamBar_ver, or empty and eventually program crashes when printing. Going back to use vol->getMCid();  allows to distinguish tunnel hits with real scifi hits. However, it is not a good solution, since this number might change of new volumes are added.

**Comment by olantwin** [comment]
What is the exact error? It appears something is missing in the `LOG(DEBUG)` line, unless `Data` is defined. Did you mean `volNameA->Data()`?

**Comment by ThomasRuf** [comment]
indeed, very strange, I thought i made a cut and paste. Here it is again, it has the ->
LOG(DEBUG)<<" current vol "<<volName->Data() <<"A node "<<volNameA->Data()<<"E node "<<volNameE->Data() ; 

The error, I explained above. Either name is blank, or something not related to Scifi, or it crashes with 

Thread 1 (Thread 0x7f26271ce740 (LWP 59814)):
#0  0x00007f2627481dff in __GI___wait4 (pid=59850, stat_loc=stat_loc
entry=0x7ffe5189ba08, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007f2627481d7b in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7ffe5189ba08, options=options
entry=0) at waitpid.c:38
#2  0x00007f26273f10e7 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
#3  0x00007f26265ca1ce in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x18fc070) at /media/disk0/SNDBuild/sw/SOURCES/ROOT/ship-v6-22-02/0/core/unix/src/TUnixSystem.cxx:2117
#4  TUnixSystem::StackTrace (this=0x18fc070) at /media/disk0/SNDBuild/sw/SOURCES/ROOT/ship-v6-22-02/0/core/unix/src/TUnixSystem.cxx:2408
#5  0x00007f2626979082 in (anonymous namespace)::do_trace (sig=1) at /media/disk0/SNDBuild/sw/SOURCES/ROOT/ship-v6-22-02/0/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:182
#6  (anonymous namespace)::TExceptionHandlerImp::HandleException (this=<optimized out>, sig=1) at /media/disk0/SNDBuild/sw/SOURCES/ROOT/ship-v6-22-02/0/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:195
#7  0x00007f26265c6eb9 in TUnixSystem::DispatchSignals (this=0x18fc070, sig=kSigSegmentationViolation) at /media/disk0/SNDBuild/sw/SOURCES/ROOT/ship-v6-22-02/0/core/unix/src/TUnixSystem.cxx:3641
#8  <signal handler called>
#9  TString::Index (this=this
entry=0xc46da28, pattern=0x7ffe5189ef69 "VTI18", plen=5, startIndex=startIndex
entry=0, cmp=cmp
entry=TString::kExact) at /media/disk0/SNDBuild/sw/SOURCES/ROOT/ship-v6-22-02/0/core/base/src/TString.cxx:877
#10 0x00007f2611dee0c9 in TString::Contains (cmp=TString::kExact, pat=..., this=<optimized out>) at /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/ROOT/ship-v6-22-02-1/include/TString.h:239
#11 Scifi::ProcessHits (this=0xaaf26f0, vol=<optimized out>) at /media/disk0/SNDBuild/sw/SOURCES/sndsw/master/0/shipLHC/Scifi.cxx:191
#12 0x00007f25f608e3e7 in FairMCApplication::Stepping (this=0xa81d780) at /media/disk0/SNDBuild/sw/SOURCES/FairRoot/v18.4.2/v18.4.2/base/sim/FairMCApplication.cxx:691
#13 0x00007f25f35c17cf in TG4SensitiveDetector::ProcessHits (this=<optimized out>, step=<optimized out>) at /media/disk0/SNDBuild/sw/SOURCES/GEANT4_VMC/v5-0-p5/v5-0-p5/source/digits+hits/src/TG4SensitiveDetector.cxx:87
#14 0x00007f25f318d46c in G4SteppingManager::Stepping() () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4tracking.so
#15 0x00007f25f31988ec in G4TrackingManager::ProcessOneTrack(G4Track*) () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4tracking.so
#16 0x00007f25f31d3b2a in G4EventManager::DoProcessing(G4Event*) () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4event.so
#17 0x00007f25f32736c7 in G4RunManager::DoEventLoop(int, char const*, int) () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4run.so
#18 0x00007f25f3271312 in G4RunManager::BeamOn(int, char const*, int) () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4run.so
#19 0x00007f25f364ab68 in TG4RunManager::ProcessRun (this=0xc45a4d0, nofEvents=147129) at /media/disk0/SNDBuild/sw/SOURCES/GEANT4_VMC/v5-0-p5/v5-0-p5/source/run/src/TG4RunManager.cxx:551
#20 0x00007f25f608db90 in FairMCApplication::RunMC (this=0xa81d780, nofEvents=147129) at /media/disk0/SNDBuild/sw/SOURCES/FairRoot/v18.4.2/v18.4.2/base/sim/FairMCApplication.cxx:461
#21 0x00007f25edd6205f in ?? ()
#22 0x0000000000000000 in ?? ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#9  TString::Index (this=this
entry=0xc46da28, pattern=0x7ffe5189ef69 "VTI18", plen=5, startIndex=startIndex
entry=0, cmp=cmp
entry=TString::kExact) at /media/disk0/SNDBuild/sw/SOURCES/ROOT/ship-v6-22-02/0/core/base/src/TString.cxx:877
#10 0x00007f2611dee0c9 in TString::Contains (cmp=TString::kExact, pat=..., this=<optimized out>) at /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/ROOT/ship-v6-22-02-1/include/TString.h:239
#11 Scifi::ProcessHits (this=0xaaf26f0, vol=<optimized out>) at /media/disk0/SNDBuild/sw/SOURCES/sndsw/master/0/shipLHC/Scifi.cxx:191
#12 0x00007f25f608e3e7 in FairMCApplication::Stepping (this=0xa81d780) at /media/disk0/SNDBuild/sw/SOURCES/FairRoot/v18.4.2/v18.4.2/base/sim/FairMCApplication.cxx:691
#13 0x00007f25f35c17cf in TG4SensitiveDetector::ProcessHits (this=<optimized out>, step=<optimized out>) at /media/disk0/SNDBuild/sw/SOURCES/GEANT4_VMC/v5-0-p5/v5-0-p5/source/digits+hits/src/TG4SensitiveDetector.cxx:87
#14 0x00007f25f318d46c in G4SteppingManager::Stepping() () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4tracking.so
#15 0x00007f25f31988ec in G4TrackingManager::ProcessOneTrack(G4Track*) () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4tracking.so
#16 0x00007f25f31d3b2a in G4EventManager::DoProcessing(G4Event*) () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4event.so
#17 0x00007f25f32736c7 in G4RunManager::DoEventLoop(int, char const*, int) () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4run.so
#18 0x00007f25f3271312 in G4RunManager::BeamOn(int, char const*, int) () from /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/GEANT4/2d174b7a10-1/lib/libG4run.so
#19 0x00007f25f364ab68 in TG4RunManager::ProcessRun (this=0xc45a4d0, nofEvents=147129) at /media/disk0/SNDBuild/sw/SOURCES/GEANT4_VMC/v5-0-p5/v5-0-p5/source/run/src/TG4RunManager.cxx:551
#20 0x00007f25f608db90 in FairMCApplication::RunMC (this=0xa81d780, nofEvents=147129) at /media/disk0/SNDBuild/sw/SOURCES/FairRoot/v18.4.2/v18.4.2/base/sim/FairMCApplication.cxx:461
#21 0x00007f25edd6205f in ?? ()
#22 0x0000000000000000 in ?? ()
===========================================================

**Comment by ThomasRuf** [comment]
ok, this web page is too stupid or wants to be too intelligent. It deleted again the arrow "->"

**Comment by olantwin** [comment]
Could you use code formatting ```?

Then code/commandline output is easier to read and Github will ignore special characters etc.

**Comment by olantwin** [comment]
I edited your comments. It appears Github was interpreting some of the <> as html.

**Comment by ThomasRuf** [comment]
sorry, but what is code formatting?

**Comment by olantwin** [comment]
https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks

**Review by antonioiuliano2 — APPROVED** [review]

**Comment by olantwin** [comment]
@ThomasRuf Is this blocked by the issue you mention above or is it OK to be merged?

**Comment by ThomasRuf** [comment]
yes, you can merge, it is not blocked by the other issue.

**Pull request merged**
