### PR TITLE
Tracking

### PR DESCRIPTION
**Pull request by siilieva**
update DS 'simple' traking

### CODE REVIEW

**Comment by siilieva** [comment]
> I am a bit sceptic about the modification to Monitor.py. I am running with several use cases, and did not came across a problem. Also, if you check line 463, there is no file extension.

**Comment by siilieva** [comment]
Sorry, dummy click to close the request..

On [146](https://github.com/SND-LHC/sndsw/blob/master/shipLHC/scripts/Monitor.py#L146) we do have an file extension

**Comment by siilieva** [comment]
> Sorry, dummy click to close the request..
> 
> On [146](https://github.com/SND-LHC/sndsw/blob/master/shipLHC/scripts/Monitor.py#L146) we do have an file extension

The problem happens when specifying a patch i.e. -P 0

**Comment by ThomasRuf** [comment]
OK, can reproduce the problem when specifying the partition. Don't understand why it works without specifying partition.

**Comment by siilieva** [comment]
> OK, can reproduce the problem when specifying the partition. Don't understand why it works without specifying partition.

Default patch value is -1, and [in that case](https://github.com/SND-LHC/sndsw/blob/master/shipLHC/scripts/Monitor.py#L449-L458) one creates a list of runs from eos and gets the filename from the list

**Comment by ThomasRuf** [comment]
now I see it. It works for eos. It would also fail if the directory is local, line 463. This confused me. This line should also be changed.

**Comment by siilieva** [comment]
I cannot reproduce the error in line 463 with local file due to a crash at init stage.
I do:
python sndsw/shipLHC/scripts/run_TrackSelections.py -o test.root -g ../geofile_sndlhc_TI18.root -r 4020
and I have the geofile and run_004020 folder with data copied locally
What command do you run to get that error?

**Comment by ThomasRuf** [comment]
Only observed that it also misses the file extension. Will have a look at the crash.

**Comment by ThomasRuf** [comment]
line 463 - 465 should be replaced by:
                     if not x.find('sndsw_raw-')<0:
                          partitions.append(x)

**Comment by siilieva** [comment]
> if not x.find('sndsw_raw-')<0:
> partitions.append(x)

Ok, that works, yes.
But then, what about the similar case in [line 142](https://github.com/SND-LHC/sndsw/blob/master/shipLHC/scripts/Monitor.py#L142)? Perhaps the same should go there? Or it works as it is?

**Comment by siilieva** [comment]
> > if not x.find('sndsw_raw-')<0:
> > partitions.append(x)
> 
> Ok, that works, yes. But then, what about the similar case in [line 142](https://github.com/SND-LHC/sndsw/blob/master/shipLHC/scripts/Monitor.py#L142)? Perhaps the same should go there? Or it works as it is?

Actually, it it the whole block that is the same : [141-144](https://github.com/SND-LHC/sndsw/blob/master/shipLHC/scripts/Monitor.py#L141-L144)

**Comment by ThomasRuf** [comment]
yes, I copied the lines. But apparently forgot to copy
source.AddFile(path+'run_'+self.runNr+'/sndsw_raw-'+str(p).zfill(4)+'.root') 
However, the inconsistency is with the list of partitions, does it contain file extension or not. Also think line 159 - 161 are wrong.

**Comment by siilieva** [comment]
I believe we're all set.

**Pull request merged**
