### PR TITLE
SndRecoTrack class addition and HT tracking updates

### PR DESCRIPTION
**Pull request by siilieva**
Main changes are
- introduction of the sndRecoTrack class - keeping information of track points, raw measurement hit/cluster times, detIDs
- changes to the HT procedure introducing tracking options for passing muons, muons form neutrino interactions, tracking with Scifi, DS, cross-system. a large variety of options controlled by a xml input file
- update the run_TrackSelector manager to run different combination of trackings at once, choosing btw output track format: genfit::Track or sndRecoTrack

### CODE REVIEW

**Comment by ThomasRuf** [comment]
there is a merge conflict with python/SndlhcTracking.py

**Comment by ThomasRuf** [comment]
Sndlhctracking: adding to ExecuteTask(self,option='ScifiDS'):
    self.fittedTracks.Delete()
is not good. The task should not be in charge of deleting, the task which creates Sndlhctracking should be in charge! otherwise, it is impossible to call the tracking task twice in an event.

**Comment by ThomasRuf** [comment]
"Don't we want to get rid of failed trackfits staight off?" If I remember correctly, making DS tracks with only two planes in each projection always produces tracks with fit failed. In addition, one might also want to study why the fit failed. So, I would leave this decision to the user of Sndlhctracking task.

**Comment by siilieva** [comment]
> Sndlhctracking: adding to ExecuteTask(self,option='ScifiDS'): self.fittedTracks.Delete() is not good. The task should not be in charge of deleting, the task which creates Sndlhctracking should be in charge! otherwise, it is impossible to call the tracking task twice in an event.

Why does one need to call ExecuteTask twice for one event?

**Comment by ThomasRuf** [comment]
muon_reco_task_Sf = SndlhcMuonReco.MuonReco()
muon_reco_task_DS = SndlhcMuonReco.MuonReco()
muon_reco_task_nuInt = SndlhcMuonReco.MuonReco()
HT_tasks = [muon_reco_task_Sf, muon_reco_task_DS, muon_reco_task_nuInt]

wouldn't it be better to have a dictionary instead of a list: HT_tasks={'muon_reco_task_nuInt':SndlhcMuonReco.MuonReco(), ...}

**Comment by siilieva** [comment]
> "Don't we want to get rid of failed trackfits staight off?" If I remember correctly, making DS tracks with only two planes in each projection always produces tracks with fit failed. In addition, one might also want to study why the fit failed. So, I would leave this decision to the user of Sndlhctracking task.

Ok, but that is bummer for sndRecoTrack class as it requres access to FitterInfo. One option would be to make an 'if' for failed track builds that would write 0/-999 for sndRecoTrack elements if fit has failed.

**Comment by ThomasRuf** [comment]
> 

Maybe for looking at a second track after having found one track, eventually with different criteria?

**Comment by ThomasRuf** [comment]
> > "Don't we want to get rid of failed trackfits staight off?" If I remember correctly, making DS tracks with only two planes in each projection always produces tracks with fit failed. In addition, one might also want to study why the fit failed. So, I would leave this decision to the user of Sndlhctracking task.
> 
> Ok, but that is bummer for sndRecoTrack class as it requres access to FitterInfo. One option would be to make an 'if' for failed track builds that would write 0/-999 for sndRecoTrack elements if fit has failed.

not sure I understand. If the information does not exist, you don't add it to the sndRecoTrack track object. The sndRecoTrack object should have a flag isFitConverged(), if yes, info exists, if not info does not exist. 
You will have a similar issue with the time information. There is no guarantee that you have a time info for all hits/clusters used by the track.

**Comment by siilieva** [comment]
> > 
> 
> Maybe for looking at a second track after having found one track, eventually with different criteria?
Changing the criteria would mean a re-init, so the track container will be flushed, no?

**Comment by ThomasRuf** [comment]
not for Sndlhctracking. Even without changing options, use case: only look for Scifi tracks if an event has a DS track.
In general, I think the tools should be stupid, and major decisions left to the master algorithm.

**Comment by siilieva** [comment]
> 



> > > "Don't we want to get rid of failed trackfits staight off?" If I remember correctly, making DS tracks with only two planes in each projection always produces tracks with fit failed. In addition, one might also want to study why the fit failed. So, I would leave this decision to the user of Sndlhctracking task.
> > 
> > 
> > Ok, but that is bummer for sndRecoTrack class as it requres access to FitterInfo. One option would be to make an 'if' for failed track builds that would write 0/-999 for sndRecoTrack elements if fit has failed.
> 
> not sure I understand. If the information does not exist, you don't add it to the sndRecoTrack track object. The sndRecoTrack object should have a flag isFitConverged(), if yes, info exists, if not info does not exist. You will have a similar issue with the time information. There is no guarantee that you have a time info for all hits/clusters used by the track.

There is a flag indicating if track fit has converged, but the track contructor from genfit::Track does not use as of now since I though we don't want failed track builds at all So I made an 'if track converged' before calling the constructor.
 I'll add the changes to the constructor depending on the track convergence. 

Why no timing info for hit/clusters? - I though one puts -999 or similar if timing info is not reasonable

**Comment by ThomasRuf** [comment]
Did you tested the Monitoring with simple tracking? I think there was a reason why self.trackTask.Init() was put at the end of the init phase.

**Comment by siilieva** [comment]
> not for Sndlhctracking. Even without changing options, use case: only look for Scifi tracks if an event has a DS track. In general, I think the tools should be stupid, and major decisions left to the master algorithm.

ok, I'll let the upper instance delete the track container for Sndlhctracking. We don't face such an issue with HT as there are separate tasks for separate tracking cases.

**Comment by siilieva** [comment]
> Did you tested the Monitoring with simple tracking? I think there was a reason why self.trackTask.Init() was put at the end of the init phase.

I didn't test the Monitoring! ah, ok will test and if problems arise, go back to init in the end.

**Comment by ThomasRuf** [comment]
sndRecoTrack::extrapolateToPlaneAtZ(float z) 
I am also doing this from time to time, but note, the detector planes are tilted in the physics coordinate system, so extrapolating to z will give a position which has a distance to the detector plane varying mainly as function of Y and a bit with X. So, it depends on the use case if it is ok or not.

**Comment by siilieva** [comment]
I'll still need to test the monitoring

**Comment by siilieva** [comment]
I checked the monitoring via the command below and it worked ok having the trackTask.Init() a bit before the end of the parent TrackSelector's Init(). For the used run I got the track plots almost identical to what we have in offline monitoring webpage. I guess tracking changed and that explains the  *almost* identical plots.
`python -i $SNDSW_ROOT/shipLHC/scripts/run_Monitoring.py -r 4361 -P 0 -p /eos/experiment/sndlhc/convertedData/commissioning/TI18/ -g ./geofile_sndlhc_TI18_V2_12July2022.root`

**Comment by ThomasRuf** [comment]
run 4361 is without Scifi! Anyhow, if you want we go ahead with merging, and I test it with one of the last runs.

**Comment by siilieva** [comment]
> run 4361 is without Scifi! Anyhow, if you want we go ahead with merging, and I test it with one of the last runs.

True, but only inside tracktask.executeevent one discriminates btw Scifi and DS. The call to the task from trackselector is one abd the same. I was saving time. Yes, lets proceed as you suggested. Thanks, Thomas!

**Review by ThomasRuf — APPROVED** [review]
OK. Let us try it out.

**Comment by siilieva** [comment]
I noticed I left the 2d event display broken - going to a dictionary of ht_tasks wasn't as straight-forward as I naively though. It is fixed now. I'll make a new branch and add up other fixes shall they arise from the monitoring test.

**Comment by ThomasRuf** [comment]
maybe false alarm, it is now stabilizing at 1.3G per job.

**Comment by siilieva** [comment]
Was that 1.3Gb the mem. consumption also before?

**Comment by ThomasRuf** [comment]
Running on another machine with the old sndsw, it seems it was 0.13GB less. However, looking at the program, nothing has really changed for the monitoring part. Running simple tracking only as before.

Von: siilieva ***@***.***>
Gesendet: Thursday, 1 December 2022 14:10
An: SND-LHC/sndsw ***@***.***>
Cc: Thomas Ruf ***@***.***>; State change ***@***.***>
Betreff: Re: [SND-LHC/sndsw] SndRecoTrack class addition and HT tracking updates (PR #133)


Was that 1.3Gb the mem. consumption also before?

**Pull request merged**
